<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>DanpheEMR.Core</AssemblyName>
    <RootNamespace>DanpheEMR.Core</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Runtime.Caching" Version="4.7.0" />
    <PackageReference Include="Audit.EntityFramework" Version="15.0.5" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
  </ItemGroup>
  <!-- Core project should not have project references -->
  <ItemGroup>
    <Compile Include="Caching.cs" />
    <Compile Include="CoreDbContext.cs" />
    <Compile Include="DynTemplates\**\*.cs" />
    <Compile Include="DynamicTemplate\**\*.cs" />
    <Compile Include="Lookups\**\*.cs" />
    <Compile Include="Parameters\**\*.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\DanpheEMR.ServerModel\DanpheEMR.ServerModel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
</Project>