CREATE OR REPLACE FUNCTION sp_exportdbtoxml()
RETURNS TABLE (
    "TABLE_CATALOG" VARCHAR,
    "TABLE_SCHEMA" VARCHAR,
    "TABLE_NAME" VARCHAR
) AS $$
BEGIN
    RETURN QUERY SELECT 'dsf_emr'::VARCHAR, 'public'::VARCHAR, 'ACC_Ledger'::VARCHAR;
END;
$$ LANGUAGE plpgsql;