CREATE OR REPLACE FUNCTION sp_phrmreport_dailystocksummaryreport(
    p_fromdate TIMESTAMP DEFAULT NULL,
    p_todate TIMESTAMP DEFAULT NULL
)
RETURNS TABLE (
    "ItemId" INT,
    "ItemName" VARCHAR,
    "BatchNo" VARCHAR,
    "GenericName" VARCHAR,
    "ExpiryDate" TIMESTAMP,
    "SalePrice" DECIMAL,
    "Price" DECIMAL,
    "OpeningQty" INT,
    "EndQty" INT
) AS $$
BEGIN
    /*
    filename: "sp_phrmreport_dailystocksummaryreport"
    createdby/date: umed/2018-02-27
    description: 
    1. created seprate function to get opention stock count of selected fromdate 
    
    2. get itemwise opening qty count, purchaseqty, purchasevalue, salesqty, salesvalue, endingqty
       (call this "getopeningstockcount" and get opening count of each items on selected date )
    remarks:    
    change history
    s.no.    updatedby/date                        remarks
    1       umed/2018-02-22	                 created the script
                                       get itemwise opening qty count, purchaseqty, purchasevalue, salesqty, salesvalue, endingqty
                                        (call this "getopeningstockcount" and get opening count of each items on selected date )
    								selecting 3 table 
    								1. in first table: selecting all dates and itemid of sales/purchase and join with second table data
    								2. in second table: selecting purchase data and doing left join with first table
    								3. third table selecting sales data and doing left join with result til generated by second table join
     2.     rusha/ 07-18-2019        updated script
     3.     rusha/ 07-21-2019        quantity is not showing correctly so updated script
     4.     rohit/13feb'23						MRP-> SalePrice
    */
    BEGIN
    	IF (
    			(p_fromdate IS NOT NULL)
    			AND (p_todate IS NOT NULL)
    			)
    	THEN
    		RETURN QUERY SELECT *
    		FROM (
    			SELECT x.ItemId
    				,x.ItemName
    				,x.BatchNo
    				,x.GenericName
    				,x.ExpiryDate
    				,x.SalePrice
    				,x.Price
    				,SUM(x.OpeningQty) AS "OpeningQty"
    				,SUM(x.EndQty) AS "EndQty"
    			FROM (
    				SELECT a.ItemId
    					,a.ItemName
    					,a.BatchNo
    					,a.GenericName
    					,a.ExpiryDate
    					,LAST_VALUE(a.SalePrice) OVER (
    						PARTITION BY a.BatchNo
    						,a.ItemId ORDER BY a.ItemId
    						) AS "SalePrice"
    					,FIRST_VALUE(a.Price) OVER (
    						PARTITION BY a.BatchNo
    						,a.ItemId ORDER BY a.ItemId
    						) AS "Price"
    					,SUM(a.OpeningQty) AS "OpeningQty"
    					,SUM(a.CurrQuantity) AS CurrQty
    					,SUM(a.OpeningQty + a.CurrQuantity) AS "EndQty"
    				FROM (
    					SELECT stock.ItemId
    						,stock.BatchNo
    						,stock.ItemName
    						,stock.GenericName
    						,0 AS "OpeningQty"
    						,SUM(stock.FreeInQty + stock.InQty - stock.OutQty - stock.FreeOutQty) AS CurrQuantity
    						,stock.ExpiryDate
    						,stock.SalePrice
    						,stock.Price
    					FROM (
    						SELECT t1.ItemId
    							,t1.BatchNo
    							,item.ItemName
    							,generic.GenericName
    							,t1.ExpiryDate
    							,LAST_VALUE(t1.SalePrice) OVER (
    								PARTITION BY t1.BatchNo
    								,t1.ItemId ORDER BY t1.ItemId
    								) AS "SalePrice"
    							,FIRST_VALUE(t1.Price) OVER (
    								PARTITION BY t1.BatchNo
    								,t1.ItemId ORDER BY t1.ItemId
    								) AS "Price"
    							,SUM(CASE 
    									WHEN InOut = 'in'
    										THEN FreeQuantity
    									ELSE 0
    									END) AS "FreeInQty"
    							,SUM(CASE 
    									WHEN InOut = 'out'
    										THEN FreeQuantity
    									ELSE 0
    									END) AS "FreeOutQty"
    							,SUM(CASE 
    									WHEN InOut = 'in'
    										THEN Quantity
    									ELSE 0
    									END) AS "InQty"
    							,SUM(CASE 
    									WHEN InOut = 'out'
    										THEN Quantity
    									ELSE 0
    									END) AS "OutQty"
    						FROM "PHRM_StockTxnItems" t1
    						INNER JOIN "PHRM_MST_Item" item ON item.ItemId = t1.ItemId
    						INNER JOIN "PHRM_MST_Generic" generic ON generic.GenericId = item.GenericId
    						WHERE (t1.CreatedOn)::DATE BETWEEN COALESCE(p_fromdate, CURRENT_TIMESTAMP)
    								AND COALESCE(p_todate, CURRENT_TIMESTAMP)
    						GROUP BY t1.ItemId
    							,t1.BatchNo
    							,item.ItemName
    							,generic.GenericName
    							,t1.ExpiryDate
    							,SalePrice
    							,Price
    						) stock
    					GROUP BY stock.ItemId
    						,stock.ItemName
    						,stock.BatchNo
    						,stock.GenericName
    						,stock.ExpiryDate
    						,stock.SalePrice
    						,stock.Price
    					
    					UNION
    					
    					SELECT stock.ItemId
    						,stock.BatchNo
    						,stock.ItemName
    						,stock.GenericName
    						,Sum(stock.FreeInQty + stock.InQty - stock.OutQty - stock.FreeOutQty) AS "OpeningQty"
    						,0 AS CurrQuantity
    						,stock.ExpiryDate
    						,stock.SalePrice
    						,stock.Price
    					FROM (
    						SELECT t1.ItemId
    							,t1.BatchNo
    							,item.ItemName
    							,generic.GenericName
    							,t1.ExpiryDate
    							,LAST_VALUE(t1.SalePrice) OVER (
    								PARTITION BY t1.BatchNo
    								,t1.ItemId ORDER BY t1.ItemId
    								) AS "SalePrice"
    							,FIRST_VALUE(t1.Price) OVER (
    								PARTITION BY t1.BatchNo
    								,t1.ItemId ORDER BY t1.ItemId
    								) AS "Price"
    							,SUM(CASE 
    									WHEN InOut = 'in'
    										THEN FreeQuantity
    									ELSE 0
    									END) AS "FreeInQty"
    							,SUM(CASE 
    									WHEN InOut = 'out'
    										THEN FreeQuantity
    									ELSE 0
    									END) AS "FreeOutQty"
    							,SUM(CASE 
    									WHEN InOut = 'in'
    										THEN Quantity
    									ELSE 0
    									END) AS "InQty"
    							,SUM(CASE 
    									WHEN InOut = 'out'
    										then quantity
    									else 0
    									end) as "outqty"
    						from "phrm_stocktxnitems" t1
    						inner join "phrm_mst_item" item on item.itemid = t1.itemid
    						inner join "phrm_mst_generic" generic on generic.genericid = item.genericid
    						where (t1.createdon)::date < coalesce(p_fromdate, current_timestamp)
    						group by t1.itemid
    							,t1.batchno
    							,item.itemname
    							,generic.genericname
    							,t1.expirydate
    							,saleprice
    							,price
    						) stock
    					group by stock.itemid
    						,stock.itemname
    						,stock.batchno
    						,stock.genericname
    						,stock.expirydate
    						,stock.saleprice
    						,stock.price
    					) a
    				group by a.itemid
    					,a.itemname
    					,a.batchno
    					,a.genericname
    					,a.expirydate
    					,a.saleprice
    					,a.price
    				) x
    			group by x.itemid
    				,x.itemname
    				,x.batchno
    				,x.genericname
    				,x.expirydate
    				,x.saleprice
    				,x.price
    			) t
    		where t.openingqty >= 0
    			and t.endqty >= 0;
    	end if;
    end;
END;
$$ LANGUAGE plpgsql;