CREATE OR REPLACE FUNCTION sp_report_bil_doctorrevenue(
    p_fromdate TIMESTAMP DEFAULT NULL,
    p_todate TIMESTAMP DEFAULT NULL,
    p_performername VARCHAR DEFAULT NULL
)
RETURNS TABLE (
    "Date" TIMESTAMP,
    "Doctor" VARCHAR,
    "USG" VARCHAR,
    "USGCOUNT" INT,
    "ORTHOPROCEDURES" VARCHAR,
    "ORTHOPROCEDURESCOUNT" INT,
    "CT" VARCHAR,
    "CTCOUNT" INT,
    "OPD" VARCHAR,
    "OPDCOUNT" INT,
    "GSURG" VARCHAR,
    "GSURGCOUNT" INT,
    "GYNSURG" VARCHAR,
    "GYNSURGCOUNT" INT,
    "ENT" VARCHAR,
    "ENTCOUNT" INT,
    "DENTAL" VARCHAR,
    "DENTALCOUNT" INT,
    "OT" VARCHAR,
    "OTCOUNT" INT
) AS $$
BEGIN
    /*  
     filename: sp_report_bil_doctorrevenue  
     created: 12dec'17 <Sudarshan>  
     Description: To Get Doctor's activity and the revenue generated by them in certain date range  
     remarks:   
     change history  
     s.no.    date/user              change          remarks  
     1.      12dec'17               created            
     2      16/04/2018-UmedSuthar     Modified   
                                   (Order By Date )  
     3.		Krishna,9thJun'22		alter				changed providerid to performerid and providername to performername
    */  
    begin  
      if (p_fromdate is not null) or (p_todate is not null)  
     then  
     RETURN QUERY SELECT (txni.billingdate)::date AS "Date",performername AS "Doctor"  
     ,sum(case when s.servicedepartmentname='USG' then txni.totalamount else 0 end) AS "USG"  
     ,sum(case when s.servicedepartmentname='USG' then txni.quantity else 0 end) AS "USGCOUNT"  
     ,sum(case when s.servicedepartmentname='Ortho Procedures' then txni.totalamount else 0 end) AS "ORTHOPROCEDURES"  
     ,sum(case when s.servicedepartmentname='Ortho Procedures' then txni.quantity else 0 end) AS "ORTHOPROCEDURESCOUNT"  
     ,sum(case when s.servicedepartmentname='CT Scan' then txni.totalamount else 0 end) AS "CT"  
     ,sum(case when s.servicedepartmentname='CT Scan' then txni.quantity else 0 end) AS "CTCOUNT"  
     ,sum(case when s.servicedepartmentname='OPD' then txni.totalamount else 0 end) AS "OPD"  
     ,sum(case when s.servicedepartmentname='OPD' then txni.quantity else 0 end) AS "OPDCOUNT"  
     ,sum(case when s.servicedepartmentname='General Surgery Charges' then txni.totalamount else 0 end) AS "GSURG"  
     ,sum(case when s.servicedepartmentname='General Surgery Charges' then txni.quantity else 0 end) AS "GSURGCOUNT"  
     ,sum(case when s.servicedepartmentname='OBS/GYN Surgery' then txni.totalamount else 0 end) AS "GYNSURG"  
     ,sum(case when s.servicedepartmentname='OBS/GYN Surgery' then txni.quantity else 0 end) AS "GYNSURGCOUNT"  
     ,sum(case when s.servicedepartmentname='ENT Operation' then txni.totalamount else 0 end) AS "ENT"  
     ,sum(case when s.servicedepartmentname='ENT Operation' then txni.quantity else 0 end) AS "ENTCOUNT"  
     ,sum(case when s.servicedepartmentname='Dental' then txni.totalamount else 0 end) AS "DENTAL"  
     ,sum(case when s.servicedepartmentname='Dental' then txni.quantity else 0 end) AS "DENTALCOUNT"  
     ,sum(case when s.servicedepartmentname='OT' then txni.totalamount else 0 end) AS "OT"  
     ,sum(case when s.servicedepartmentname='OT' then txni.quantity else 0 end) AS "OTCOUNT"  
     from "fn_bil_getactivebiltxnitemsofdoctors"() txni, bil_mst_servicedepartment s  
     where txni.performername is not null and txni.servicedepartmentid=s.servicedepartmentid  
      and txni.billingdate between p_fromdate and p_todate+1 -- todate+1 since input comes as: 2017-06-22 12:00:00 am from datepicker.  
      and txni.performername like '%'||coalesce(p_performername,'')||'%'  
      and 1 = ( case when s.servicedepartmentname !='OPD' then 1   
                when s.servicedepartmentname = 'OPD' and txni.requisitionid not in   
                                                   (select distinct initialvisitid   
                    from fn_appt_getreferalvisitinformation()) then 1 else 0 end)  
         
     group by (txni.billingdate)::date, performername  
     order by date desc , performername;  
      end if;--end of if  
    end;--end of sp
END;
$$ LANGUAGE plpgsql;