CREATE PROCEDURE [dbo].[SP_PHRMReport_DailyStockSummaryReport] @FromDate DATETIME = NULL
	,@ToDate DATETIME = NULL
AS
/*
FileName: [SP_PHRMReport_DailyStockSummaryReport]
CreatedBy/date: Umed/2018-02-27
Description: 
1. Created Seprate Function to Get Opention Stock Count of Selected FromDate 

2. Get ItemWise Opening Qty Count, PurchaseQty, PurchaseValue, SalesQty, SalesValue, EndingQty
   (Call this [getOpeningStockCount] and Get Opening Count of Each Items on Selected Date )
Remarks:    
Change History
S.No.    UpdatedBy/Date                        Remarks
1       Umed/2018-02-22	                 created the script
                                   Get ItemWise Opening Qty Count, PurchaseQty, PurchaseValue, SalesQty, SalesValue, EndingQty
                                    (Call this [getOpeningStockCount] and Get Opening Count of Each Items on Selected Date )
								Selecting 3 Table 
								1. In First Table: Selecting All Dates and ItemId of Sales/Purchase and Join with Second Table Data
								2. In Second Table: Selecting Purchase Data and Doing Left Join With First TAble
								3. Third Table Selecting Sales Data and Doing Left join with Result Til Generated by Second Table Join
 2.     Rusha/ 07-18-2019        updated script
 3.     Rusha/ 07-21-2019        quantity is not showing correctly so updated script
 4.     Rohit/13Feb'23						MRP-> SalePrice
*/
BEGIN
	IF (
			(@FromDate IS NOT NULL)
			AND (@ToDate IS NOT NULL)
			)
	BEGIN
		SELECT *
		FROM (
			SELECT x.ItemId
				,x.ItemName
				,x.BatchNo
				,x.GenericName
				,x.ExpiryDate
				,x.SalePrice
				,x.Price
				,SUM(x.OpeningQty) AS OpeningQty
				,SUM(x.EndQty) AS EndQty
			FROM (
				SELECT a.ItemId
					,a.ItemName
					,a.BatchNo
					,a.GenericName
					,a.ExpiryDate
					,LAST_VALUE(a.SalePrice) OVER (
						PARTITION BY a.BatchNo
						,a.ItemId ORDER BY a.ItemId
						) 'SalePrice'
					,FIRST_VALUE(a.Price) OVER (
						PARTITION BY a.BatchNo
						,a.ItemId ORDER BY a.ItemId
						) 'Price'
					,SUM(a.OpeningQty) AS OpeningQty
					,SUM(a.CurrQuantity) AS CurrQty
					,SUM(a.OpeningQty + a.CurrQuantity) AS EndQty
				FROM (
					SELECT stock.ItemId
						,stock.BatchNo
						,stock.ItemName
						,stock.GenericName
						,0 AS OpeningQty
						,SUM(stock.FreeInQty + stock.InQty - stock.OutQty - stock.FreeOutQty) AS CurrQuantity
						,stock.ExpiryDate
						,stock.SalePrice
						,stock.Price
					FROM (
						SELECT t1.ItemId
							,t1.BatchNo
							,item.ItemName
							,generic.GenericName
							,t1.ExpiryDate
							,LAST_VALUE(t1.SalePrice) OVER (
								PARTITION BY t1.BatchNo
								,t1.ItemId ORDER BY t1.ItemId
								) 'SalePrice'
							,FIRST_VALUE(t1.Price) OVER (
								PARTITION BY t1.BatchNo
								,t1.ItemId ORDER BY t1.ItemId
								) 'Price'
							,SUM(CASE 
									WHEN InOut = 'in'
										THEN FreeQuantity
									ELSE 0
									END) AS 'FreeInQty'
							,SUM(CASE 
									WHEN InOut = 'out'
										THEN FreeQuantity
									ELSE 0
									END) AS 'FreeOutQty'
							,SUM(CASE 
									WHEN InOut = 'in'
										THEN Quantity
									ELSE 0
									END) AS 'InQty'
							,SUM(CASE 
									WHEN InOut = 'out'
										THEN Quantity
									ELSE 0
									END) AS 'OutQty'
						FROM [dbo].[PHRM_StockTxnItems] t1
						INNER JOIN [dbo].[PHRM_MST_Item] item ON item.ItemId = t1.ItemId
						INNER JOIN [dbo].[PHRM_MST_Generic] generic ON generic.GenericId = item.GenericId
						WHERE CONVERT(DATE, t1.CreatedOn) BETWEEN ISNULL(@FromDate, GETDATE())
								AND ISNULL(@ToDate, GETDATE())
						GROUP BY t1.ItemId
							,t1.BatchNo
							,item.ItemName
							,generic.GenericName
							,t1.ExpiryDate
							,SalePrice
							,Price
						) stock
					GROUP BY stock.ItemId
						,stock.ItemName
						,stock.BatchNo
						,stock.GenericName
						,stock.ExpiryDate
						,stock.SalePrice
						,stock.Price
					
					UNION
					
					SELECT stock.ItemId
						,stock.BatchNo
						,stock.ItemName
						,stock.GenericName
						,Sum(stock.FreeInQty + stock.InQty - stock.OutQty - stock.FreeOutQty) AS OpeningQty
						,0 AS CurrQuantity
						,stock.ExpiryDate
						,stock.SalePrice
						,stock.Price
					FROM (
						SELECT t1.ItemId
							,t1.BatchNo
							,item.ItemName
							,generic.GenericName
							,t1.ExpiryDate
							,LAST_VALUE(t1.SalePrice) OVER (
								PARTITION BY t1.BatchNo
								,t1.ItemId ORDER BY t1.ItemId
								) 'SalePrice'
							,FIRST_VALUE(t1.Price) OVER (
								PARTITION BY t1.BatchNo
								,t1.ItemId ORDER BY t1.ItemId
								) 'Price'
							,SUM(CASE 
									WHEN InOut = 'in'
										THEN FreeQuantity
									ELSE 0
									END) AS 'FreeInQty'
							,SUM(CASE 
									WHEN InOut = 'out'
										THEN FreeQuantity
									ELSE 0
									END) AS 'FreeOutQty'
							,SUM(CASE 
									WHEN InOut = 'in'
										THEN Quantity
									ELSE 0
									END) AS 'InQty'
							,SUM(CASE 
									WHEN InOut = 'out'
										THEN Quantity
									ELSE 0
									END) AS 'OutQty'
						FROM [dbo].[PHRM_StockTxnItems] t1
						INNER JOIN [dbo].[PHRM_MST_Item] item ON item.ItemId = t1.ItemId
						INNER JOIN [dbo].[PHRM_MST_Generic] generic ON generic.GenericId = item.GenericId
						WHERE CONVERT(DATE, t1.CreatedOn) < ISNULL(@FromDate, GETDATE())
						GROUP BY t1.ItemId
							,t1.BatchNo
							,item.ItemName
							,generic.GenericName
							,t1.ExpiryDate
							,SalePrice
							,Price
						) stock
					GROUP BY stock.ItemId
						,stock.ItemName
						,stock.BatchNo
						,stock.GenericName
						,stock.ExpiryDate
						,stock.SalePrice
						,stock.Price
					) a
				GROUP BY a.ItemId
					,a.ItemName
					,a.BatchNo
					,a.GenericName
					,a.ExpiryDate
					,a.SalePrice
					,a.Price
				) x
			GROUP BY x.ItemId
				,x.ItemName
				,x.BatchNo
				,x.GenericName
				,x.ExpiryDate
				,x.SalePrice
				,x.Price
			) t
		WHERE t.OpeningQty >= 0
			AND t.EndQty >= 0
	END
END