--Altering SP_Report_BIL_DoctorRevenue SP
--changed ProviderId to PerformerId and ProviderName to PerformerName
CREATE PROCEDURE [dbo].[SP_Report_BIL_DoctorRevenue]   
 @FromDate DateTime=null,  
 @ToDate DateTime=null,  
 @PerformerName varchar(70)=null  
 AS  
/*  
 FileName: SP_Report_BIL_DoctorRevenue  
 Created: 12Dec'17 <Sudarshan>  
 Description: To Get Doctor's Activity and the Revenue generated by them in certain date range  
 Remarks:   
 Change History  
 S.No.    Date/User              Change          Remarks  
 1.      12Dec'17               created            
 2      16/04/2018-UmedSuthar     Modified   
                               (Order By Date )  
 3.		Krishna,9thJun'22		alter				changed ProviderId to PerformerId and ProviderName to PerformerName
*/  
BEGIN  
  IF (@FromDate IS NOT NULL) OR (@ToDate IS NOT NULL)  
 BEGIN  
 SELECT Convert(date,txnI.BillingDate) 'Date',PerformerName 'Doctor'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='USG' THEN txnI.TotalAmount ELSE 0 END) AS 'USG'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='USG' THEN txnI.Quantity ELSE 0 END) AS 'USGCOUNT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='Ortho Procedures' THEN txnI.TotalAmount ELSE 0 END) AS 'ORTHOPROCEDURES'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='Ortho Procedures' THEN txnI.Quantity ELSE 0 END) AS 'ORTHOPROCEDURESCOUNT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='CT Scan' THEN txnI.TotalAmount ELSE 0 END) AS 'CT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='CT Scan' THEN txnI.Quantity ELSE 0 END) AS 'CTCOUNT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='OPD' THEN txnI.TotalAmount ELSE 0 END) AS 'OPD'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='OPD' THEN txnI.Quantity ELSE 0 END) AS 'OPDCOUNT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='General Surgery Charges' THEN txnI.TotalAmount ELSE 0 END) AS 'GSURG'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='General Surgery Charges' THEN txnI.Quantity ELSE 0 END) AS 'GSURGCOUNT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='OBS/GYN Surgery' THEN txnI.TotalAmount ELSE 0 END) AS 'GYNSURG'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='OBS/GYN Surgery' THEN txnI.Quantity ELSE 0 END) AS 'GYNSURGCOUNT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='ENT Operation' THEN txnI.TotalAmount ELSE 0 END) AS 'ENT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='ENT Operation' THEN txnI.Quantity ELSE 0 END) AS 'ENTCOUNT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='Dental' THEN txnI.TotalAmount ELSE 0 END) AS 'DENTAL'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='Dental' THEN txnI.Quantity ELSE 0 END) AS 'DENTALCOUNT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='OT' THEN txnI.TotalAmount ELSE 0 END) AS 'OT'  
 ,SUM(CASE WHEN s.ServiceDepartmentName='OT' THEN txnI.Quantity ELSE 0 END) AS 'OTCOUNT'  
 FROM [FN_BIL_GetActiveBilTxnItemsOfDoctors]() txnI, BIL_MST_ServiceDepartment s  
 WHERE txnI.PerformerName is not null and txnI.ServiceDepartmentId=s.ServiceDepartmentId  
  AND txnI.BillingDate between @FromDate and @ToDate+1 -- todate+1 since input comes as: 2017-06-22 12:00:00 AM from DatePicker.  
  AND txnI.PerformerName like '%'+ISNULL(@PerformerName,'')+'%'  
  AND 1 = ( CASE WHEN s.ServiceDepartmentName !='OPD' THEN 1   
            WHEN s.ServiceDepartmentName = 'OPD' AND txni.RequisitionId NOT IN   
                                               (select distinct InitialVisitId   
                from FN_APPT_GetReferalVisitInformation()) THEN 1 ELSE 0 END)  
     
 GROUP BY Convert(date,txnI.BillingDate), PerformerName  
 ORDER BY DATE desc , PerformerName  
  End--end of IF  
End--end of SP